# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 303a547ce5a4818480a416a25dd1ab2869870275b7cc562320ac09c1f93eab7e9bb229e0f5ffa0f8a710f5ed6a35747eb101bc85661c9a455f10a2a6175ebe60

test:
  secret_key_base: 4dbfa22b672b30af45d29170c33d996150cd58e5fef445c5d82b9f678cfc350f1fc068bf95ca953e8377ea803294dba34919f3deefa4bf284825de529b347447

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
